"""initial tables

Revision ID: 1024a92c1883
Revises: 
Create Date: 2026-10-03 12:41:42.182138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base


# revision identifiers, used by Alembic.
revision: str = '1024a92c1883'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('notified_at', app.models.base.UTCDateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_users_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('google_sub', name=op.f('uq_users_google_sub'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('target_playlist_id', sa.String(length=64), nullable=True),
    sa.Column('target_playlist_title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), nullable=False),
    sa.Column('finished_at', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('fatal_error_status', sa.Integer(), nullable=True),
    sa.Column('fatal_error_reason', sa.String(length=64), nullable=True),
    sa.Column('fatal_error_message', sa.Text(), nullable=True),
    sa.Column('rate_limit_attempt', sa.Integer(), nullable=True),
    sa.Column('rate_limit_retry_at', app.models.base.UTCDateTime(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'stopped')", name=op.f('ck_jobs_status')),
    sa.CheckConstraint("type IN ('remove_like', 'move', 'move_and_unlike', 'playlist_remove')", name=op.f('ck_jobs_type')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_user_id_status', ['user_id', 'status'], unique=False)

    op.create_table('oauth_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.String(length=1024), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_oauth_tokens'))
    )
    op.create_table('quota_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_pt', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quota_usage_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quota_usage'))
    )
    with op.batch_alter_table('quota_usage', schema=None) as batch_op:
        batch_op.create_index('ix_quota_usage_date_pt', ['date_pt'], unique=False)

    op.create_table('job_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('video_title', sa.Text(), nullable=False),
    sa.Column('playlist_item_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_reason', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'success', 'failed', 'skipped', 'rollback_failed', 'not_processed')", name=op.f('ck_job_items_status')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_items_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_items'))
    )
    with op.batch_alter_table('job_items', schema=None) as batch_op:
        batch_op.create_index('ix_job_items_job_id_position', ['job_id', 'position'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_items', schema=None) as batch_op:
        batch_op.drop_index('ix_job_items_job_id_position')

    op.drop_table('job_items')
    with op.batch_alter_table('quota_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_quota_usage_date_pt')

    op.drop_table('quota_usage')
    op.drop_table('oauth_tokens')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_user_id_status')

    op.drop_table('jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
